<?php	
/**
 * Product media data template
 *
 * @see Mage_Catalog_Block_Product_View_Media
 */

/* @var $this Mage_Catalog_Block_Product_View_Media */
?>
<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
?>
<div class="product-image product-image-zoom">
    <div class="product-image-gallery">
        <img id="image-main"
             class="gallery-image visible"
             src="<?php echo $this->helper('catalog/image')->init($_product, 'image') ?>"
             alt="<?php echo $this->escapeHtml($this->getImageLabel()) ?>"
             data-zoom-image="<?php echo $this->helper('catalog/image')->init($_product, 'image') ?>"
             title="<?php echo $this->escapeHtml($this->getImageLabel()); ?>" />
    </div>
</div>

<?php if (count($this->getGalleryImages()) > 0): ?>
<div class="more-views">
    <h2><?php echo $this->__('More Views') ?></h2>
    <ul  id="gallery" class="product-image-thumbs">
    <?php $i=0; foreach ($this->getGalleryImages() as $_image): ?>
        <?php
        if (($filterClass = $this->getGalleryFilterHelper()) && ($filterMethod = $this->getGalleryFilterMethod()) && !Mage::helper($filterClass)->$filterMethod($_product, $_image)):
            continue;
        endif;
        ?>
        <li>
            <a href="javascript:void(0);" class="thumb-link" href="#" title="<?php echo $this->escapeHtml($_image->getLabel()) ?>"  data-image="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(75); ?>" data-zoom-image="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile()); ?>">
                <img  src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(75); ?>"
                     width="75" height="75" alt="<?php echo $this->escapeHtml($_image->getLabel()) ?>" />
            </a>
        </li>
    <?php $i++; endforeach; ?>
    </ul>
</div>
<?php endif; ?>
<?php echo $this->getChildHtml('after'); ?>
<script type="text/javascript">
//<![CDATA[
	jQuery("#image-main").elevateZoom({gallery:'gallery',  galleryActiveClass: 'active'});
    jQuery('#image-main').bind("click", function(e) { 
		var ez = jQuery('#image-main').data('elevateZoom');	
		console.log(ez.getGalleryList());
		jQuery.fancybox(ez.getGalleryList());
		return false; 
	});
//]]>
</script>
